# This is a basic workflow to help you get started with Actions

name: portfolio-application

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the portfolio-app branch
  push:
    branches: [ portfolio-app ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2-beta
      with: 
        version: 14
      #Create a build
    - name: Creating build
      run: npm run build
    
    - name: installing surge  
      run: npm install -g surge
    
    - name: deploying on surge
      run: surge ./build https://portfolio-spa.surge.sh --token ${{secrets.SURGE_TOKEN}}